## Phase -2 Numpy Array Oprations

In [13]:
import numpy as np

In [14]:
arr = np.array([1,2, 3 ,4 ,5 ,6, 7 ,8, 9, 10])
print("Basic Slicing:", arr[2:5])

print("With Steps Slicing:", arr[2:8:2])


print("Negavtive Slicing:", arr[-2])


Basic Slicing: [3 4 5]
With Steps Slicing: [3 5 7]
Negavtive Slicing: 9


In [15]:
arr_2d= np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])



print("Specific Elements:",arr_2d[1,2])

print("Entire Row: ", arr_2d[1])


print("Entire Row: ", arr_2d[:,1])




Specific Elements: 6
Entire Row:  [4 5 6]
Entire Row:  [2 5 8]


# Sorting

In [16]:
unsorted = np.array([2,4,342,13,23])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D Array by column", np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D Array by Rows", np.sort(arr_2d_unsorted,axis=1))

Sorted Array [  2   4  13  23 342]
Sorted 2D Array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array by Rows [[1 3]
 [1 2]
 [2 3]]


# Filterning 

In [17]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)



Even numbers:  [ 2  4  6  8 10]


## Filter with Masks

In [18]:
mask = numbers > 5
print("Number greater then 5 are: ",numbers[mask] )

Number greater then 5 are:  [ 6  7  8  9 10]


## Fancy Indexing VS np.where()

In [19]:
indices = [0,1,2,3,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("Where result: ", numbers[where_result])

[1 2 3 4 5]
Where result:  [ 6  7  8  9 10]


## Condition Array

In [20]:
condition_array = np.where(numbers > 5 ,"True" , "False" )
print(condition_array)


['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


## Adding and Removing Data

In [21]:
arr1 = np.array ([1,2,3]
                 )
arr2 = np.array ([4,5,6]
                 )

combined =np.concatenate(( arr1 , arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibilty

In [22]:
a = np.array ([1 , 2, 3])
b = np.array ([4 , 5, 6])
c = np.array ([7 , 8, 9])

print("Compatibility Shape" , a.shape==b.shape)

Compatibility Shape True


## Dont Know what to Give the Name 

In [23]:
orginial = np.array([[1,2],[3,4]])
new_rows = np.array([[5,6]])

with_new_rows = np.vstack((orginial,new_rows))
print("Original\n",orginial,"\nNew\n",new_rows,"\nWth New rows\n",with_new_rows)

new_col = np.array([[7] ,  [8]])
with_new_col= np.hstack((orginial , new_col))
print("with col", with_new_col)

Original
 [[1 2]
 [3 4]] 
New
 [[5 6]] 
Wth New rows
 [[1 2]
 [3 4]
 [5 6]]
with col [[1 2 7]
 [3 4 8]]


## Deletation

In [24]:
arr = np.array([1, 2, 3, 4])
deleted = np.delete(arr,1)
print("Array after deletion",deleted)



Array after deletion [1 3 4]
