## Numpy Basic

In [1]:
import numpy as np

## Creating Array from list

In [2]:
arr_1 = np.array([1,1,2,4])
print("1D arry",arr_1)

arr_2 = np.array ([[1,2,3] , [4,5,6]])
print("2D arry",arr_2)

1D arry [1 1 2 4]
2D arry [[1 2 3]
 [4 5 6]]


## List Vs numpy Aarray

In [3]:
py_list = [1,2,3]
print("Python list Multiplication", py_list * 2)


np_array = np.array([1,2,3,4])    ## Element wise Multiplication
print("Numpy Array Multiplication", np_array * 2)

import time
start= time.time()
py_list = [i*2 for i in range(100000)]
print("\n List opration time: " , time.time()- start)

start= time.time()
np_array= np.arange(100000 *2 )
print("\n Numpy opration time: " , time.time()- start)




Python list Multiplication [1, 2, 3, 1, 2, 3]
Numpy Array Multiplication [2 4 6 8]

 List opration time:  0.005951642990112305

 Numpy opration time:  0.0006995201110839844


## Creating Array From Scractch

In [4]:
zeros =  np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((3,4))
print("Ones array: \n",ones)

full = np.full((2,2),7)
print("full array: \n",full)



random = np.random.random((2,4))
print("Random array: \n",random)

sequence = np.arange(0,10,2)
print("sequence array: \n",sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.60302272 0.25818108 0.4743599  0.50290706]
 [0.77884362 0.32098761 0.49376888 0.35881866]]
sequence array: 
 [0 2 4 6 8]


## Vectos , Matrix And Tensor 

In [5]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])

print("Matrix: ",matrix)


Tensor = np.array([[[1,2],[3,5]]
                   ,[[5,6],[6,8]]])
print("Tencor: ",Tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tencor:  [[[1 2]
  [3 5]]

 [[5 6]
  [6 8]]]


## Array Properties

In [6]:
arr = np.array([[1,2,3],
                [4,5,'Suraj']])

print("Shape of array:",arr.shape)
print("Dimensions of array:",arr.ndim)
print("Size of array:",arr.size)
print("Data Type:",arr.dtype)



Shape of array: (2, 3)
Dimensions of array: 2
Size of array: 6
Data Type: <U21


## Array Reshaping 

In [7]:
arr = np.arange(12)
print("Orginal Array: ", arr)


reshaped= arr.reshape((3,4))
print("reshaped Array: ", reshaped)

flattend = reshaped.flatten()
print("flattend Array", flattend)


reveled= reshaped.ravel()   #### Return View,  Instead of copy 
print("reveled Array", reveled)


## Transpose
transpoase = reshaped.T
print("transpoased Array", transpoase)


Orginal Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpoased Array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
