## Practice Day1 (Easy Questions) -->Date: 23-6-2025

In [4]:
## 1. Create a 1D NumPy array containing numbers from 0 to 9.  (Date: 23-6-2025)

import numpy as np 

## 1st Way 
arr_1d = np.array ([1 , 2 , 3, 4, 5, 6, 7, 8, 9, 10])
print("\nCreating array in 1st way: ", arr_1d)
print("Type of array: ",type(arr_1d))


## 2nd Way

arr_1d_2nd_way = np.arange(0,11)
print("\nCreating array in 2nd way:", arr_1d_2nd_way)
print("Type of array: ",type(arr_1d_2nd_way))




Creating array in 1st way:  [ 1  2  3  4  5  6  7  8  9 10]
Type of array:  <class 'numpy.ndarray'>

Creating array in 2nd way: [ 0  1  2  3  4  5  6  7  8  9 10]
Type of array:  <class 'numpy.ndarray'>


In [5]:
## 2. Create a 3x3 NumPy array filled with zeros.

## 1st Way
arra3x3 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print("\nCreating arra3x3 array in 1st way:",arra3x3)
print("Type of array: ",type(arra3x3))


## 2nd Way

arra3x3_2nd_way = np.random.rand(3,3)
print("\nCreating arra3x3 array in 2nd way:",arra3x3_2nd_way)
print("Type of array: ",type(arra3x3_2nd_way))



## 3rd Way 

arra3x3_zeros  = np.zeros((3,3),int)
print(arra3x3_zeros)



Creating arra3x3 array in 1st way: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type of array:  <class 'numpy.ndarray'>

Creating arra3x3 array in 2nd way: [[0.27326472 0.13821542 0.66106117]
 [0.2600116  0.11495161 0.68420047]
 [0.22262534 0.25174692 0.63385229]]
Type of array:  <class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
## 3. Create a NumPy array of 10 random integers between 1 and 100.

arrayrandom = np.random.randint(1,100, size=10)
print("Creating arrayrandom array: ",arrayrandom)


Creating arrayrandom array:  [77 19 77 73 22 11 35 82 77 31]


In [7]:
## 4. Find the mean and standard deviation of a NumPy array.

arraytocheck = np.random.randint(3,10, size=(3,3))
print("Array Created below\n",arraytocheck)

## Mean
mean_arraytocheck = np.mean(arraytocheck)
print("\nMean of the array is: ", mean_arraytocheck)

## Standard deviation
std_devi = np.std(arraytocheck)
print("Standard deviation of the array is: ", std_devi)

Array Created below
 [[7 4 4]
 [7 3 3]
 [3 5 7]]

Mean of the array is:  4.777777777777778
Standard deviation of the array is:  1.6850834320114558


In [8]:
## 5. Convert a list [1, 2, 3, 4] to a NumPy array.

list= [1, 2, 3, 4, 5]
print("\nType of the current provided is:", type(list))

convert = np.array(list)
print("\nAfter converting from list to array: ",convert)
print("Type is list provided: ",type(convert))


Type of the current provided is: <class 'list'>

After converting from list to array:  [1 2 3 4 5]
Type is list provided:  <class 'numpy.ndarray'>


In [9]:
## 6. Create a 2D array with shape (2, 3) filled with ones.

array = np.ones((2,3))
print(array)

array = np.zeros((2,3))
print(array)



[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
## 7. Find the maximum and minimum values in a NumPy array.

findmax = np.max(arra3x3)
findmin = np.min(arra3x3)
print("Finding the max and min from the below array\n",arra3x3)
print("Max value is: ",findmax)
print("Min value is: ",findmin)

Finding the max and min from the below array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Max value is:  9
Min value is:  1


In [11]:
 ## 9. Reshape a 1D array of 9 elements into a 3x3 2D array.

arr_1d = np.arange(1,10)
print("1d Aary is: ",arr_1d)

reshaped = np.reshape (arr_1d,shape=(3,3))
print("After Reshaping the Array\n",reshaped)


1d Aary is:  [1 2 3 4 5 6 7 8 9]
After Reshaping the Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
## 10.Get the shape and datatype of a NumPy array.

arr_1d = np.arange(1,10)
print("1d Aary is: ",arr_1d)

reshaped = np.reshape (arr_1d,shape=(3,3))
print("After Reshaping the Array\n",reshaped)

print("Shape of the Array",np.shape(reshaped))
print("Datatype of the Array",reshaped.dtype)



1d Aary is:  [1 2 3 4 5 6 7 8 9]
After Reshaping the Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of the Array (3, 3)
Datatype of the Array int64


In [13]:
## 11. Perform element-wise addition of two NumPy arrays.

add_array_1 = np.random.randint (1,10, size=(3,3))
add_array_2 = np.random.randint (11,20,size=(3,3))

addition = add_array_1 + add_array_2
print("First Array:\n", add_array_1)
print("Second Array:\n", add_array_2)
print("Addition of arrays are:\n ", addition) 



First Array:
 [[5 4 4]
 [6 9 8]
 [5 6 1]]
Second Array:
 [[14 12 14]
 [11 14 14]
 [14 16 13]]
Addition of arrays are:
  [[19 16 18]
 [17 23 22]
 [19 22 14]]


In [14]:
## 12. Create an array of even numbers from 2 to 20.

arr1 = np.arange(2,21)

even= arr1[arr1 % 2 ==0]
print("Even Number in arrays are", even)

Even Number in arrays are [ 2  4  6  8 10 12 14 16 18 20]
