## Practice Day -2  (Easy Questions) --> Date: 24-6-2025

In [87]:
## 1. Generate an array of 5 random integers between 10 and 50. (Date: 24-6-2025)

import numpy as np

array1 = np.random.randint(10,20 ,size=5)
print("Array of 5 random integers between 10 and 50",array1)

Array of 5 random integers between 10 and 50 [12 17 18 16 17]


In [88]:
## 2. Create an identity matrix of size 4x4.

array2 = np.random.rand(4,4)
print(array2)

[[0.9491066  0.15240454 0.993014   0.64368141]
 [0.96049881 0.45839786 0.55341483 0.31021599]
 [0.47999258 0.74773116 0.7168159  0.13447805]
 [0.8390646  0.99711942 0.8523057  0.67859602]]


In [89]:
## 3. Find the sum of all elements in a NumPy array.

sumaaray = sum(array2)
print("sum of all elements in a NumPy array is:",sumaaray)   ## sum function will return the sum of the columns

sum of all elements in a NumPy array is: [3.22866259 2.35565299 3.11555043 1.76697147]


In [90]:
## 4. Create an array of 10 zeros and change the fifth value to 1.

new_array = np.zeros((10))
print(new_array)

new_array[:5]=1
print(new_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [91]:
## 5. Get the maximum and minimum values from a NumPy array.

print("Maximum number of array2 is: ",max(array1))
print("Maximum number of array2 is: ",min(array1))

Maximum number of array2 is:  18
Maximum number of array2 is:  12


In [92]:
## 5. Reverse a NumPy array using slicing.

print("Before",array1)
reverse = array1[::-1]
print("After ",reverse)

Before [12 17 18 16 17]
After  [17 16 18 17 12]


In [93]:
## 6. Generate a linearly spaced array between 0 and 1 with 10 elements.

spaced = np.arange(1,11,2)
print("arange spaced array between 0 and 1 with 10 elements.",spaced)

spaced = np.linspace(0,10)
print("linearly spaced array between 0 and 1 with 10 elements.\n",spaced)  ### need to check this. 

arange spaced array between 0 and 1 with 10 elements. [1 3 5 7 9]
linearly spaced array between 0 and 1 with 10 elements.
 [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [94]:
## 7. Convert a Python list to a NumPy array.

list = [1, 2, 3, 4, 5]
print(f"Type {list} is:",type(list))

convert = np.array(list)
print(f"Type {convert} is:",type(convert))



Type [1, 2, 3, 4, 5] is: <class 'list'>
Type [1 2 3 4 5] is: <class 'numpy.ndarray'>


In [95]:
## 8. Find the shape and data type of a NumPy array.

print(f"The shape of {convert} is: ",np.shape(convert))
print(f"The Datatype of {convert} is: ",convert.dtype)

The shape of [1 2 3 4 5] is:  (5,)
The Datatype of [1 2 3 4 5] is:  int64


In [96]:
## 9. Create a 3x3 matrix with values from 1 to 9.

matrix = np.random.randint(1,10,size=(3,3)
                           )

print(" 3x3 matrix with values from 1 to 9 is \n.",matrix)

 3x3 matrix with values from 1 to 9 is 
. [[7 6 3]
 [4 6 4]
 [1 1 2]]


In [97]:
## 10. Sort a NumPy array in ascending order.
print("The Orginial Maxtrix is\n",matrix)
print("The sorted Maxtrix Array columns wise as we have axis=0 is below\n ",np.sort(matrix,axis=0))
print("The sorted Maxtrix Array rows wise as we have axis=1 is below\n ",np.sort(matrix,axis=1))

The Orginial Maxtrix is
 [[7 6 3]
 [4 6 4]
 [1 1 2]]
The sorted Maxtrix Array columns wise as we have axis=0 is below
  [[1 1 2]
 [4 6 3]
 [7 6 4]]
The sorted Maxtrix Array rows wise as we have axis=1 is below
  [[3 6 7]
 [4 4 6]
 [1 1 2]]


In [98]:
## 11. Extract the diagonal elements from a 2D array.



matrix = np.random.randint(1, 10, size=(3, 3))
diagonal_elements = np.diagonal(matrix)
print("Matrix:\n", matrix)
print("Diagonal elements:", diagonal_elements)


Matrix:
 [[6 5 1]
 [1 9 6]
 [8 6 6]]
Diagonal elements: [6 9 6]


In [99]:
## 12. Check whether each element in an array is greater than 10.

matrix = np.random.randint(1, 20, size=(3, 3))
print(matrix)

matrix[matrix > 10] = 1

print(matrix)




[[11  5 14]
 [ 7 16  5]
 [ 5  4 16]]
[[1 5 1]
 [7 1 5]
 [5 4 1]]


In [100]:
## 13. Find the standard deviation and mean of a NumPy array.
print("Matrix:\n", matrix)
print("The mean of the matrix is:" ,np.mean(matrix))
print("The standard deviation of the matrix is:" ,np.std(matrix))

Matrix:
 [[1 5 1]
 [7 1 5]
 [5 4 1]]
The mean of the matrix is: 3.3333333333333335
The standard deviation of the matrix is: 2.211083193570267


In [101]:
## 14. Replace all negative values in a NumPy array with zero.

zeros = np.array([1, -1, 2 ,-2, 3, -3, 4, -4])

print("original matrix is: ",zeros)
zeros[zeros < 1]=0
print("Changed matriz is: ",zeros)

original matrix is:  [ 1 -1  2 -2  3 -3  4 -4]
Changed matriz is:  [1 0 2 0 3 0 4 0]


In [102]:
## 15 . Repeat an array of [1, 2, 3] three times.

repeat = np.tile([1,2,3],(3,1))

print(repeat)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [103]:
## 16. Split a 1D array into 3 equal parts.


zeros = np.array([1, -1, 2 ,-2, 3, -3, 4, -4,5])
print(zeros)


spilt = np.split(zeros,3)
print(spilt)

[ 1 -1  2 -2  3 -3  4 -4  5]
[array([ 1, -1,  2]), array([-2,  3, -3]), array([ 4, -4,  5])]


In [104]:
## 17.Stack two 1D arrays vertically.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


stacked = np.vstack((a, b))

print("Vertically stacked array:\n", stacked)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]]


In [105]:
## 18. Find the number of non-zero elements in a NumPy array.
matrix = np.random.randint(0, 20, size=(3, 3))
print(matrix)

nonzero = np.count_nonzero(matrix)

print(nonzero)

[[17  0 10]
 [11 19 17]
 [ 4  1  5]]
8


In [106]:
## 19. Create a 5x5 matrix with random integers and clip values above 50.

new = np.random.randint(40,100,size=(5,5))
print("Before updating the values which is greathen 50:\n",new)

new[new > 50]=50
print("After updating the values which is greathen 50:\n",new)

Before updating the values which is greathen 50:
 [[44 61 72 62 55]
 [41 52 87 60 73]
 [60 64 72 42 56]
 [66 40 67 74 46]
 [97 40 76 88 59]]
After updating the values which is greathen 50:
 [[44 50 50 50 50]
 [41 50 50 50 50]
 [50 50 50 42 50]
 [50 40 50 50 46]
 [50 40 50 50 50]]


In [107]:
## 20. Create an array of 10 elements and print only the odd numbers.

new = np.array([[10, 15, 22], [33, 44, 55], [60, 71, 80], [99,44,67]])
print("We will perform the operation in the below array:\n", new)


# Step 2: Filter odd numbers
odd = new[new % 2 != 0].tolist()
print("\nAfter filtering, only odd values:\n", odd)


We will perform the operation in the below array:
 [[10 15 22]
 [33 44 55]
 [60 71 80]
 [99 44 67]]

After filtering, only odd values:
 [15, 33, 55, 71, 99, 67]


In [108]:
## 21. Find the cumulative sum of elements in a NumPy array.

print(odd)

cumulative = np.cumsum(odd)
print(cumulative)


[15, 33, 55, 71, 99, 67]
[ 15  48 103 174 273 340]


In [109]:
## 22. Create a boolean mask for values greater than the average.

arr = np.array([30, 40, 50, 60, 70])

mean = np.mean(arr)
print(f"The mean of the array {arr} is: {mean}\n")

mask = arr > mean
print(mask)




The mean of the array [30 40 50 60 70] is: 50.0

[False False False  True  True]


In [110]:
## 23. Generate a random float array of size 4x4 between 0 and 1.

arr = np.random.rand(4,4 )
print(arr)

[[0.58762472 0.66249864 0.97240824 0.27860859]
 [0.74983594 0.12102393 0.34921318 0.91601365]
 [0.60509268 0.00705975 0.00592052 0.7658718 ]
 [0.53041887 0.59433574 0.51037037 0.87070497]]


In [111]:
## 24. Check if two NumPy arrays are equal.

arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr2 =  np.array([[1,2,3],
                [4,5,6],
                [7,8,9]]) 
a= np.equal(arr1,arr2)
print(a)

b = np.array_equal (arr1 , arr2)
print("\n",b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

 True


In [112]:
## 25. Flatten a multi-dimensional array to 1D.

print(f"Array befor flatten:\n{arr2}")
print(f"Array After flatten:\n",arr2.flatten())


Array befor flatten:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array After flatten:
 [1 2 3 4 5 6 7 8 9]


In [113]:
## 26. Get the indices of maximum and minimum values in a NumPy array.

arr = np.array([1,2,3,4])
print(f"The indices of maximum for array {arr} is: {np.argmax(arr)}")
print(f"The indices of minimum for array {arr} is: {np.argmin(arr)}")


The indices of maximum for array [1 2 3 4] is: 3
The indices of minimum for array [1 2 3 4] is: 0


In [114]:
## 27. Generate a 6x6 matrix with values from 0 to 35 and reshape.

arr = np.random.randint(0,36,size=(6,6))
print(arr)

reshape = np.reshape(arr,shape=(3,12))
print(reshape)

[[32 29 15 19 30 19]
 [19 32 13 10 11  4]
 [18 23 34  6 31 11]
 [12 35  4 27 21 10]
 [14  8 16 20 23 35]
 [ 1 10  6  5 35 20]]
[[32 29 15 19 30 19 19 32 13 10 11  4]
 [18 23 34  6 31 11 12 35  4 27 21 10]
 [14  8 16 20 23 35  1 10  6  5 35 20]]


In [115]:
## 28. Create a matrix with a border of 1s and 0 inside (5x5).

arr = np.ones((5,5), dtype=int)
print(arr)

arr [1:-1,1:-1]=0
print(arr)



[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [116]:
## 29. Use arange() to create an array from 5 to 50 with step 5.
arr = np.arange(5,50,5)
print(arr)


[ 5 10 15 20 25 30 35 40 45]


In [117]:
## 30 . Print only unique values from a NumPy array.

arr = np.array([2,2,2,2,4,5])
print(np.unique(arr))

[2 4 5]


In [118]:
## 31. Count how many times each value appears in a NumPy array.

arr = np.array([2,2,2,2,4,5])
print(np.unique_counts(arr))

UniqueCountsResult(values=array([2, 4, 5]), counts=array([4, 1, 1]))


In [119]:
## 32. Create an array of floats and convert it to integers.

arr = np.random.rand(2,2)
print(arr)

convert =  arr.astype(int)
print(convert)

[[0.73905556 0.81967124]
 [0.14037037 0.49135264]]
[[0 0]
 [0 0]]
