## Practice Day 4  Intermidate Level   Date: 26-06-2025

In [2]:
## 1. 

import numpy as np

# Input data
animals = np.array(["cat", "dog", "dog", "fish"])

# Step 1: Find unique categories
unique_animals = np.unique(animals)

# Step 2: Create a mapping from category to index
animal_to_index = {animal: idx for idx, animal in enumerate(unique_animals)}

# Step 3: Initialize one-hot encoded matrix
one_hot = np.zeros((animals.shape[0], unique_animals.shape[0]), dtype=int)

# Step 4: Set the appropriate position to 1
for i, animal in enumerate(animals):
    index = animal_to_index[animal]
    one_hot[i, index] = 1

print("Original labels:", animals)
print("One-hot encoded:\n", one_hot)


Original labels: ['cat' 'dog' 'dog' 'fish']
One-hot encoded:
 [[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]]


In [3]:
## 2. Compute dot product and cross product of two vectors.

vect_1 = np.array([1,2,3,4,5,6,7])
vect_2 = np.array([8,9,10,11,12,13,14])

dot = np.dot(vect_1 , vect_2)
print(f"The Dot product of {vect_1} and {vect_2} is:",dot)

cross = np.cross(vect_1[:3] , vect_2[:3])
print(f"The Cross product of first three values for {vect_1} and {vect_2} is:",cross)

The Dot product of [1 2 3 4 5 6 7] and [ 8  9 10 11 12 13 14] is: 336
The Cross product of first three values for [1 2 3 4 5 6 7] and [ 8  9 10 11 12 13 14] is: [-7 14 -7]


In [4]:
## 3. Find the determinant of a 2D square matrix.

arr_1 = np.random.randint(10,20, size=(3,3))

deter = np.linalg.det(arr_1)
print(f"The determinant of the {arr_1} is:", deter)

The determinant of the [[19 10 15]
 [14 14 14]
 [12 12 10]] is: -252.00000000000003


In [5]:
## 4. Create an array of dates using `np.datetime64`.

arr_date = np.arange('2025-01','2025-12',dtype='datetime64[M]')
print(arr_date)

['2025-01' '2025-02' '2025-03' '2025-04' '2025-05' '2025-06' '2025-07'
 '2025-08' '2025-09' '2025-10' '2025-11']


In [32]:
## 5. Add padding of zeros around a 2D array.

arr = np.random.randint(10,20,size=(2,2))

pad = np.pad(arr ,pad_width=1,mode="constant",constant_values=0)
print("With constant\n",pad)

pad1 = np.pad(arr, pad_width=((2, 2), (2, 2)), mode='edge')
print("With edge\n",pad1)


With constant
 [[ 0  0  0  0]
 [ 0 13 12  0]
 [ 0 17 17  0]
 [ 0  0  0  0]]
With edge
 [[13 13 13 12 12 12]
 [13 13 13 12 12 12]
 [13 13 13 12 12 12]
 [17 17 17 17 17 17]
 [17 17 17 17 17 17]
 [17 17 17 17 17 17]]


In [33]:
## 6. Use `meshgrid` to create a coordinate matrix.

a = np.array([1,2])
b = np.array([2,4])

c = np.meshgrid(a,b)
print(c)

(array([[1, 2],
       [1, 2]]), array([[2, 2],
       [4, 4]]))


In [ ]:
## 7. Create a frequency table from a 1D NumPy array.

import numpy as np

# Sample 1D array
arr = np.array([2, 3, 2, 5, 3, 2, 1, 5, 5, 5, 3])

# Get unique values and their counts
values, counts = np.unique(arr, return_counts=True)

# Display frequency table
for v, c in zip(values, counts):
    print(f"Value {v} appears {c} times")


Value 1 appears 1 times
Value 2 appears 3 times
Value 3 appears 3 times
Value 5 appears 4 times
