## Practice Day 3  Intermidate Level   Date: 25-06-2025

In [12]:
## 1. Create a 3D NumPy array and access its middle layer.

import numpy as np

arr = np.random.randint(10,25, size=(3,3,3))
print(f"Random Array is\n {arr}\n array ends")

middile = arr[1:-1]
print("start",middile)



Random Array is
 [[[20 22 19]
  [20 22 24]
  [22 20 24]]

 [[13 10 21]
  [21 20 11]
  [19 16 23]]

 [[14 23 16]
  [21 11 10]
  [18 11 22]]]
 array ends
start [[[13 10 21]
  [21 20 11]
  [19 16 23]]]


In [19]:
## 2. Broadcast a 1D array to a 2D array and add them.

arr = np.array([1,2,3,4])
arr2 = np.random.randint(100,120, size=(4,3))


reshaped = arr.reshape(4,1)
print(reshaped)
print(arr2)

addition = reshaped + arr2 
print(addition)

[[1]
 [2]
 [3]
 [4]]
[[103 114 104]
 [112 110 112]
 [100 101 108]
 [106 105 106]]
[[104 115 105]
 [114 112 114]
 [103 104 111]
 [110 109 110]]


In [26]:
## 3. Filter out NaN values from a NumPy array.

arr = np.array([1,2,np.nan,4,np.nan])

filtered_arr = arr[~np.isnan(arr)]

print("Original Array:", arr)
print("Filtered Array (no NaNs):", filtered_arr)


Original Array: [ 1.  2. nan  4. nan]
Filtered Array (no NaNs): [1. 2. 4.]


In [31]:
## 4. Replace elements less than 0 in an array with their absolute values.

arr = np.array([1,2,-1,4,-5,-6])

arr[arr < 0] = np.abs(arr[ arr< 0 ])

print(arr)

[1 2 1 4 5 6]


In [33]:
# 5. Perform matrix multiplication between two arrays.

arr = np.array([1,2,-1,4,-5,-6])
arr2 = np.array([1,2,-1,4,-5,-6])

mul = np.matmul(arr,arr2)
print(mul)

83


In [39]:
# 6. Find the row-wise sum of a 2D NumPy array.

arr = np.array([[1,2],[-1,4],[-5,-6]])

arr2 = np.array([[1,2],[-1,4],[-5,-6]])

sum1 = np.sum(arr,axis=1)
sum2= np.sum(arr2,axis=1)


print(sum,sum2)





[  3   3 -11] [  3   3 -11]


In [41]:
# 7. Extract the second column from a 2D NumPy array.

arr = np.random.randint (2,10,size=(2,2))
print(arr)

print(arr[-1])

[[4 8]
 [2 2]]
[2 2]


In [75]:
## 8. Use `where()` to find elements that satisfy multiple conditions.

arr = np.random.randint (2,10,size=(2,2))
print(arr)
condition = np.where (((arr > 2) & (arr <3 )), 1,7 )
print(condition)

[[4 4]
 [4 2]]
[[7 7]
 [7 7]]


In [77]:
## 9. Compute the moving average of a 1D NumPy array.

arr = np.array([1,2,-1,4,-5,-6])
arr2 = np.array([1,2,-1,4,-5,-6])

print(np.convolve(arr,arr2))


[  1   4   2   4   7 -40   2 -28 -23  60  36]


In [83]:
## 10. Generate a 10x10 matrix and normalize it (0 to 1).

arr = np.random.randint(10,50,size=(10,10))

normal = (arr - np.min(arr)) / (np.max(arr)- np.min(arr))

print(normal)

[[0.64102564 0.97435897 0.51282051 0.64102564 0.94871795 0.58974359
  0.         0.15384615 0.94871795 0.84615385]
 [0.46153846 0.64102564 0.79487179 0.41025641 0.38461538 0.8974359
  0.76923077 0.53846154 0.58974359 0.79487179]
 [0.69230769 0.25641026 0.07692308 0.15384615 0.12820513 0.66666667
  0.17948718 0.15384615 0.1025641  0.84615385]
 [0.23076923 0.84615385 1.         0.8974359  0.74358974 0.38461538
  0.92307692 0.30769231 0.25641026 0.17948718]
 [1.         0.76923077 0.30769231 0.12820513 0.87179487 0.61538462
  0.84615385 0.28205128 0.15384615 0.58974359]
 [0.         0.48717949 0.58974359 0.76923077 0.8974359  0.12820513
  0.23076923 0.25641026 0.74358974 0.07692308]
 [0.38461538 0.46153846 0.66666667 0.64102564 0.53846154 0.61538462
  0.33333333 0.61538462 0.76923077 0.53846154]
 [0.53846154 0.30769231 1.         0.58974359 0.05128205 0.94871795
  0.92307692 0.20512821 0.12820513 0.1025641 ]
 [0.12820513 0.87179487 0.1025641  0.07692308 0.87179487 0.84615385
  0.48717949 

In [85]:
## 11. Use `argmax()` and `argmin()` with axis parameter.

arr = np.random.randint(10,50,size=(3,3))
print(arr)

print(np.argmax(arr , axis=1))
print(np.argmin(arr , axis=0))

[[40 39 47]
 [29 48 24]
 [41 45 28]]
[2 1 1]
[1 0 1]


In [87]:
## 12. Sort a 2D array row-wise and column-wise.

arr = np.random.randint(10,50,size=(3,3))
print(arr)

print(np.sort(arr , axis=1))
print(np.sort(arr , axis=0))
print(np.ndim(arr))

[[27 30 19]
 [31 20 10]
 [37 26 24]]
[[19 27 30]
 [10 20 31]
 [24 26 37]]
[[27 20 10]
 [31 26 19]
 [37 30 24]]
2


In [93]:
## 13. Split an array into uneven parts and handle the remainder.

arr = np.random.randint(10,50,size=(3,3))
print(arr)
np.array_split(arr,2)

[[25 42 15]
 [31 13 23]
 [31 20 32]]


[array([[25, 42, 15],
        [31, 13, 23]], dtype=int32),
 array([[31, 20, 32]], dtype=int32)]

In [ ]:
## 13. Create a correlation matrix using random data.
arr = np.array([1,2,-1,4,-5,-6])
arr1 = np.array([1,2,-1,4,-5,-6])

print( np.correlate(arr, arr2))  ### its used for checking the correlation between 1d arrays


### its used for checking the correlation between 2d arrays

##  from scipy.signal import correlate2d
##  correlate2d(matrix1, matrix2, mode='valid')


[83]


In [103]:
## 14. Find all indices of a specific value in a NumPy array.

a=10
arr = np.array ([1,2,3,4,5,6,7,8,9,10])

condition = np.where(arr >= a, "True", arr )
print(condition)

['1' '2' '3' '4' '5' '6' '7' '8' '9' 'True']


In [ ]:
## 15. Replace all NaNs in a 2D array with the column mean.

arr = np.array([[1,2],[np.nan,4]])

filtered_arr = arr[~np.isnan(arr)]
